### ISSUE TITLE
Couldn't find Git Bash (Installation issues)

### ISSUE THREAD

**Issue by garthbjerk** [VerifiableRobotics/LTLMoP#49]
When I try to run setup.py, I get the error message that it can't find the Git Bash. Attached is an image of my files. They're all in the G:\ directory.
![file](https://f.cloud.github.com/assets/5796316/1422012/5a18119e-3ff5-11e3-882f-ff9bb665e2f1.png)

**Comment by cfinucane** [comment]
The setup script assumes Git Bash is installed into the default location (e.g. `%ProgramFiles%`), since it's not clear to me how else to find it without searching the whole computer.  You can manually override it by editing here: https://github.com/LTLMoP/LTLMoP/blob/development/dist/gitUtils.py#L30 .   That said, if you can come up with a better general solution it would be very much appreciated.

**Comment by cfinucane** [comment]
Alternatively, and perhaps more simply, you can just open up a Git Bash terminal yourself and run the script from inside it.  That should bypass the need for it to find Git Bash entirely.

**Comment by garthbjerk** [comment]
Thank you for the information. I opted to use the terminal to run the
script from inside it and it worked fine.

On Mon, Oct 28, 2013 at 10:44 AM, Cameron Finucane <notifications@github.com
